version: 2.1
jobs:
  build:
    working_directory: ~/iris-dataset-lr
    steps:
      - run:
          name: Install dependencies
          command: |
            pipenv --python 3.9
            pipenv shell
            pipenv install
      - run:
          name: Run script
          command: |
            python3 logistic_regression.py
