version: 2.1
jobs:
  build:
    working_directory: ~/repo
    steps:
      - run:
          name: Install dependencies
          command: |
            pipenv --python 3.9
            pipenv shell
            pipenv install
      - run:
          name: Run script
          command: |
            python3 logistic_regression.py
      - run:
          name: Run tests
          command: |
            python3 test_logistic_regression.py
      - store_artifacts:
          path: lr_model.pkl
